openapi: 3.0.0
info:
  title: Store Management API
  description: API that acts as a store management tool.
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server